---
- hosts: localhost
  vars_files:
    - settings.yml
    - ['/home/seed/cloudbox/accounts.yml', '/home/seed/cloudbox/accounts.yml.default']
    - ['/home/seed/cloudbox/settings.yml', '/home/seed/cloudbox/settings.yml.default']
    - ['/home/seed/cloudbox/adv_settings.yml', '/home/seed/cloudbox/adv_settings.yml.default']
  roles:
    - { role: pre_tasks }
    - { role: user }
    - { role: airdcpp, tags: ['airdcpp'] }
